# Testing properties precedence
test-property: source-dan-service-tech-starter-application-yaml

dan:
  kafka:
    producer:
      topics:
        logs: dan-service-logs

spring:
  cloud:
    kubernetes:
      loadbalancer:
        mode: SERVICE
    consul:
      config:
        format: yaml
        enabled: true
        fail-fast: true
        profileSeparator: '-'
        watch:
          enabled: true
      host: consul-server
      port: 8500
  config:
    import: "optional:consul:${spring.cloud.consul.host}:${spring.cloud.consul.port}/"
  kafka:
    bootstrap-servers: dan-kafka-cluster-kafka-bootstrap:9092
    consumer:
      group-id: ${spring.application.name}

management:
  endpoint:
    env:
      # For testing property values, not safe for PROD
      show-values: ALWAYS
    health:
      show-details: "ALWAYS"
  endpoints:
    web:
      base-path: /
      exposure:
        include: "*"
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin:9411/api/v2/spans
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true